from agents.lm_studio import lm_studio
import logging

logger = logging.getLogger(__name__)

async def research_topic(topic: str) -> dict:
    """Phase 4: Research Copilot utilizing Gemma 4"""
    if await lm_studio.is_available():
        try:
            prompt = f"Act as a Research Copilot. Summarize key papers and findings on '{topic}'."
            messages = [{"role": "system", "content": "You are a research copilot."}, {"role": "user", "content": prompt}]
            summary = await lm_studio.chat(messages, temperature=0.3)
            return {"topic": topic, "summary": summary, "sources": ["mock_arxiv.org", "mock_scholar.google"]}
        except Exception as e:
            logger.error(f"Gemma 4 Research failed: {e}")
    
    return {"topic": topic, "summary": f"Mock research summary for {topic} generated by Research Agent.", "sources": []}
